version: '3.8'

services:
  api:
    container_name: ${PROJECT_NAME:-app}-api-dev
    environment:
      - NODE_ENV=development
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    container_name: ${PROJECT_NAME:-app}-web-dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
